[package]
name = "example-memory"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.5.13"
axum-login = { path = "../../" }

[dependencies.rand]
version = "0.8.5"
features = ["min_const_gen"]

[dependencies.tokio]
version = "1.0"
features = ["full"]
